# Generated by Django 5.0 on 2023-12-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
