# Generated by Django 5.0 on 2023-12-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='index',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='zipcode',
        ),
    ]
